/**
 * EAPCET Chapter-wise syllabus for Mathematics, Physics, and Chemistry.
 * Used for chapter-wise quiz categorization and question tagging.
 */

export const EAPCET_CHAPTERS = {
  Mathematics: [
    'Functions',
    'Mathematical Induction',
    'Matrices',
    'Complex Numbers',
    "De Moivre's Theorem",
    'Quadratic Expressions',
    'Theory of Equations',
    'Permutations and Combinations',
    'Binomial Theorem',
    'Trigonometric Ratios up to Transformations',
    'Trigonometric Equations',
    'Inverse Trigonometric Functions',
    'Hyperbolic Functions',
    'Properties of Triangles',
    'Addition of Vectors',
    'Product of Vectors',
    'Measures of Dispersion',
    'Probability',
    'Random Variables and Probability Distributions',
    'Locus',
    'Transformation of Axes',
    'The Straight Line',
    'Pair of Straight lines',
    'Circle',
    'System of circles',
    'Parabola',
    'Ellipse',
    'Hyperbola',
    'Three Dimensional Coordinates',
    'Direction Cosines and Direction Ratios',
    'Plane',
    'Limits and Continuity',
    'Differentiation',
    'Applications of Derivatives',
    'Integration',
    'Definite Integrals',
    'Differential equations',
  ],
  Physics: [
    'Physical World',
    'Units and Measurements',
    'Motion in a Straight Line',
    'Motion in a Plane',
    'Laws of Motion',
    'Work, Energy and Power',
    'System of Particles and Rotational Motion',
    'Oscillations',
    "Gravitation: Kepler's Laws",
    'Mechanical Properties of Solids',
    'Mechanical Properties of Fluids',
    'Thermal Properties of Matter',
    'Thermodynamics',
    'Kinetic Theory',
    'Waves',
    'Ray Optics and Optical Instruments',
    'Wave Optics',
    'Electric Charges and Fields',
    'Electrostatic Potential and Capacitance',
    'Current Electricity',
    'Moving Charges and Magnetism',
    'Magnetism and Matter',
    'Electromagnetic Induction',
    'Alternating Current',
    'Electromagnetic Waves',
    'Dual Nature of Radiation and Matter',
    'Atoms',
    'Nuclei',
    'Semiconductor Electronics',
    'Communication Systems',
  ],
  Chemistry: [
    'Atomic Structure',
    'Classification of Elements and Periodicity in Properties',
    'Chemical Bonding and Molecular Structure',
    'States of Matter: Gases and Liquids',
    'Stoichiometry',
    'Thermodynamics',
    'Chemical Equilibrium and Acids-Bases',
    'Hydrogen and its Compounds',
    'The s-Block Elements (Alkali and Alkaline Earth Metals)',
    'p- Block Elements Group 13 (Boron Family)',
    'p-Block Elements – Group 14 (Carbon Family)',
    'Environmental Chemistry',
    'Organic Chemistry',
    'Solid State',
    'Solutions',
    'Electrochemistry and Chemical Kinetics',
    'Surface Chemistry',
    'General Principles of Metallurgy',
    'P-Block Elements',
    'd And f Block Elements & Coordination Compounds',
    'Polymers',
    'Biomolecules',
    'Chemistry in Everyday Life',
    'Halo Alkanes and Halo Arenes',
  ],
} as const;

export type Subject = keyof typeof EAPCET_CHAPTERS;
